apiVersion: apps/v1
kind: Deployment
metadata:
  name: telegram-autoregexbot
  labels:
    app: telegram-autoregexbot
spec:
  replicas: 1
  selector:
    matchLabels:
      app: telegram-autoregexbot
  template:
    metadata:
      labels:
        app: telegram-autoregexbot
    spec:
      containers:
        - name: bot
          image: ghcr.io/santarl/telegram-autoregexbot:b3c202e1d5569b64922d96e7d5d4658c4ced7a48
          env:
            - name: BOT_TOKEN
              valueFrom:
                secretKeyRef:
                  name: autoregex-telegram-bot-token
                  key: TOKEN
