apiVersion: apps/v1
kind: Deployment
metadata:
  name: telegram-autoregexbot
  labels:
    app: telegram-autoregexbot
spec:
  replicas: 1
  selector:
    matchLabels:
      app: telegram-autoregexbot
  template:
    metadata:
      labels:
        app: telegram-autoregexbot
    spec:
      containers:
        - name: bot
          image: ghcr.io/santarl/telegram-autoregexbot:56bd997a2fa94b141a694e422972abf396d4a38c
          env:
            - name: BOT_TOKEN
              valueFrom:
                secretKeyRef:
                  name: autoregex-telegram-bot-token
                  key: TOKEN
          volumeMounts:
            - name: autoregexbot-config-volume
              mountPath: /app/autoregexbot.cfg
              subPath: autoregexbot.cfg
      volumes:
        - name: autoregexbot-config-volume
          configMap:
            name: autoregexbot-config
